### PR TITLE
two-space indent for qcjson part

### PR DESCRIPTION
**Pull request by mgcam**

### CODE REVIEW

**Comment by mgcam** [comment]
>
> The reason I closed the request was that I did not see that the proposed
> changes added anything useful to the charts.
>
Of course. However, not all pull requests offer new/improved features, many of them deal with housekeeping issues. The proposed changes make the indentation consistent, GitHub friendly and conforming to NPG coding standards (also recommended on a javascript course we both went to) - all valid reasons to have it.

**Comment by jenniferliddle** [comment]
I've double checked the existing bcviz graphs, and all of them have consistent indents of 4, not 2.
I am unaware of any NPG coding standards that mandate 2 character indents rather than 4. The majority of existing NPG code uses 4.
Best Practice for javascript is an indent of 4, according to crockford http://javascript.crockford.com/code.html, Guzel http://code.tutsplus.com/tutorials/top-15-best-practices-for-writing-super-readable-code--net-8118, iMarc http://handbook.imarc.net/javascript, and http://programmers.stackexchange.com/questions/9584/php-html-javascript-and-writing-good-practices
stevekwan, on the other hand, says "It just isn't worth the effort obsessing over rigid indentation/squiggly rules. Do what you think makes sense in the given context. If your code is readable and clear, it should speak for itself regardless of the indentation style you choose". https://github.com/stevekwan/best-practices/blob/master/javascript/best-practices.md
I think these are all valid reasons to leave the indentation at 4.

**Comment by jmtcsngr** [comment]
There a few lines in tests which have very long arrays. Will it be worth breaking those lines to no more than 80 chars? I will do a pull request to Marinas code for an example.

**Comment by jmtcsngr** [comment]
I was checking and there a few very long lines in the tests. You think is worth breaking them?

**Comment by jmtcsngr** [comment]
Sorry, my computer is going into super slow mode. I may be posting twice.
I think they were tabs before they were changed into spaces. I vote for spaces.

**Comment by dkj** [comment]
Final call on indentation policy is Marina's.

**Comment by mgcam** [comment]
On 08/04/2015 16:43, jmtcsngr wrote:
>
> Sorry, my computer is going into super slow mode. I may be posting twice.
> I think they were tabs before they were changed into spaces. I vote 
> for spaces.
>
Yes, it's about having consistently spaces everywhere, not tabs, so the 
code can be easily edited and displayed in different ad hoc editors.




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Pull request merged**
